    tokens.append(Token("symbol", "("))
    tokens.append(Token("integerConstant", "1"))
    tokens.append(Token("symbol", ","))
    tokens.append(Token("stringConstant", "Hello"))
    tokens.append(Token("symbol", ")"))